[luck-d]
title = "LUCKY DRAW"
url = "https://www.luck-d.com/home/"
entrySelector = "div.gallery div.gallery_cell_layer"
titleSelector = "h5 a"
linkSelector = "h5 a"
contentSelector = "div.agent_site_info p"
imageSelector = "div.product_thumb_layer a img"
waitUntil = "networkidle"

[grandstage]
title = "ABC마트 그랜드스테이지 온라인몰"
url = "https://grandstage.a-rt.com/display/calendar"
entrySelector = "li[class='col-list-item prod-item draw-item']"
titleSelector = "span.prod-name"
linkSelector = "a"
contentSelector = "span.sale-period"
imageSelector = "div.img-wrap img"
waitForSelector = ".launching-calendar-list"
