[luck-d]
title = "LUCKY DRAW"
url = "https://www.luck-d.com/home/"
entrySelector = "div.gallery div.gallery_cell_layer"
titleSelector = "h5 a"
linkSelector = "h5 a"
contentSelector = "div.agent_site_info p"
imageSelector = "div.product_thumb_layer a img"
waitUntil = "networkidle"
onFail = "stale"

[ssmuniverse]
title = "스스므 ─ DRAW"
url = "https://ssmuniverse.com/board?category=12"
entrySelector = "div.exsi-item.grid.overflow-hidden a.card-item.grid-item.view-hidden"
titleSelector = "div.column-title.noto-h4.column-mb-15.text-break.text-overflow-3"
linkSelector = "*"
contentSelector = "div.column-content.noto-pr.mb-5.column-lineheight.w-100.text-break.text-overflow-5"
imageSelector = "img.column-img"
waitUntil = "networkidle"
onFail = "stale"

[shoeprize]
title = "슈프라이즈"
url = "https://www.shoeprize.com/"
entrySelector = "ul.product_list li"
titleSelector = "div.name"
linkSelector = "div.img_area a"
contentSelector = "div.text_area"
waitUntil = "networkidle"
onFail = "stale"

[shoeprize_ko]
title = "슈프라이즈"
url = "https://www.shoeprize.com/today/?filter={%22excludeKor%22:0,%22includeKor%22:1,%22excludeEnd%22:0}"
entrySelector = "ul.product_list li"
titleSelector = "div.name"
linkSelector = "div.img_area a"
contentSelector = "div.text_area"
waitUntil = "networkidle"
onFail = "stale"

[musinsa]
title = "무신사 ─ Raffle"
url = "https://store.musinsa.com/app/raffle/lists"
entrySelector = "a.view"
titleSelector = "strong.tit"
linkSelector = "*"
contentSelector = "*"
imageSelector = "img"
waitForSelector = "ul.raffle-list li a.view"
onFail = "stale"
