[nike_launch_upcoming]
title = "NIKE ─ SNKRS ─ Upcoming"
url = "https://www.nike.com/kr/launch/?type=upcoming"
entrySelector = "ul[class='item-list-wrap upcoming-section bg-white ncss-row prl2-md prl5-lg pb4-md pb6-lg  gallery'] li[class='launch-list-item item-imgwrap pb2-sm va-sm-t ncss-col-sm-12 ncss-col-md-6 ncss-col-lg-4 pb4-md prl0-sm prl2-md ncss-col-sm-6 ncss-col-lg-3 pb4-md prl2-md pl0-md pr1-md d-sm-h d-md-ib  upcomingItem complete']"
titleSelector = "div[class='launch-caption ta-sm-c']"
linkSelector = "a[class='card-link d-sm-b comingsoon']"
contentSelector = "div[class='copy-container ta-sm-c bg-white pt6-sm pb7-sm pb7-lg']"
waitForSelector = "div.pt4-md.pt6-lg.feed-container ul li"

[luck-d]
title = "LUCKY DRAW"
url = "https://www.luck-d.com/home/"
entrySelector = "div.gallery div.gallery_cell_layer"
titleSelector = "h5 a"
linkSelector = "h5 a"
contentSelector = "div.agent_site_info p"
imageSelector = "div.product_thumb_layer a img"
waitUntil = "networkidle"
onFail = "stale"

[ssmuniverse]
title = "스스므 ─ DRAW"
url = "https://ssmuniverse.com/board?category=12"
entrySelector = "div.exsi-item.grid.overflow-hidden a.card-item.grid-item.view-hidden"
titleSelector = "div.column-title.noto-h4.column-mb-15.text-break.text-overflow-3"
linkSelector = "*"
contentSelector = "div.column-content.noto-pr.mb-5.column-lineheight.w-100.text-break.text-overflow-5"
imageSelector = "img.column-img"
waitUntil = "networkidle"
onFail = "stale"
